# Makefile - dimanet main makefile
# License-Identifier: GPL-3.0
# Latest updated version: v1.3

# WARNING: subdirectory makefile

# DOCUMENTATION
# ----------------------------------------
# See 'make help' or the main Makefile from
# root directory

FORM = $(MAKE) -C ../../

all:
	@$(FORM) all
sigmoid:
	@$(FORM) sigmoid
threshold:
	@$(FORM) threshold
linear:
	@$(FORM) linear
debug:
	@$(FORM) debug
example:
	@$(FORM) example
map:
	@$(FORM) map
wheel:
	@$(FORM) wheel
book:
	@$(FORM) book
clean:
	@$(FORM) clean
bclean:
	@$(FORM) bclean
xclean:
	@$(FORM) xclean
mclean:
	@$(FORM) mclean
start:
	@$(FORM) start
help:
	@$(FORM) help

.PHONY: sigmoid threshold linear debug example map wheel book clean clean bclean xclean mclean start help
